### ISSUE TITLE
Add back "content-editable" instructions.

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-resources#28]
Took it out of the lesson for time, but I ended up covering it anyway and it didn't actually take that long.

```
{{#unless isEditable}}
  <h4>#{{pokemon.nationalPokeNum}} : {{pokemon.name}}</h4>
  <p> Generation: {{pokemon.generation}} </p>
  <p>
    Type(s): {{pokemon.typeOne}}
    {{#if twoTypes}}
      / {{pokemon.typeTwo}}
    {{/if}}
  </p>
{{else}}
  <h4>#{{input value=pokemon.nationalPokeNum}} : {{input value=pokemon.name}}</h4>
  <p> Generation: {{input value=pokemon.generation}} </p>
  <p>
    Type(s): {{input value=pokemon.typeOne}}
    {{#if twoTypes}}
      / {{input value=pokemon.typeTwo}}
    {{/if}}
  </p>
{{/unless}}
<button {{action 'updatePokemon'}}>EDIT</button>
<button {{action 'destroyPokemon'}}>DESTROY</button>
```

**Comment by jrhorn424** [comment]
In my most recent delivery, I gave in-place editing as a challenge instead of making it part of the lesson. This gave the lesson focus on using ember routes for transitioning viewstate and also gave us a chance to practice using different components for storing form data.

**Comment by GA-MEB** [comment]
@jrhorn424 
Do you have the details of that challenge recorded anywhere?

**Comment by jrhorn424** [comment]
@GA-MEB Sorry, I didn't document it. Totally my fault. It was an on-the-fly decision that I think worked out well. I'll add in instructions on the next iteration.

**Comment by jrhorn424** [comment]
Moving forward we will use handlebars control flow and component state to switch which templates get rendered (a form or table).
