### ISSUE TITLE
Spin out Ember actions into separate repo?

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-resources#31]
One of the big conceptual stumbling blocks, but it doesn't strictly need to be put together with CRUD.

**Comment by jrhorn424** [comment]
This is still worth considering for a future iteration, IMO.

**Comment by jrhorn424** [comment]
This has largely been addressed by focusing on binding data and actions down, but dispatching action execution upward. We now go into detail about bindings as you had originally suggested, @GA-MEB.
